# Generated by Django 4.0 on 2021-12-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_completed_task_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='body',
            new_name='description',
        ),
    ]
